version: 2.1

orbs:
  windows: circleci/windows@2.2.0
commands:
  restoreandpublish:
    description: "Restore dependencies and build app for production inside an out directory"
    steps:
      - run: "dotnet restore"
      - run: "mkdir out"
      - run: "dotnet publish -c Release -o out"
  testapplication:
    description: "Run application tests"
    steps:
      - run: "dotnet test"
jobs:
  runtests: description
  build:
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout
      - testapplication
      - restoreandpublish
      - store_artifacts:
          path: C:\Users\circleci\project\out
          destination: TODOAPP
